name: Feature Request / Suggestion
description: Suggest an improvement or new feature for WoW Cleanup Tool
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees:
  - Myrroddin
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please fill out the sections below to help us understand your request.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have read the documentation ([README](https://github.com/Myrroddin/wow-cleanup-tool/blob/main/README.md) and [Technical Details](https://github.com/Myrroddin/wow-cleanup-tool/blob/main/Technical-Details.md))
          required: false

  - type: dropdown
    id: request-type
    attributes:
      label: Request Type
      description: What kind of suggestion is this?
      options:
        - New Feature
        - Enhancement to Existing Feature
        - UI/UX Improvement
        - Performance Improvement
        - Documentation Improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe clearly what the problem is.
      placeholder: "I'm always frustrated when..."
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: "As an alternative, we could..."
    validations:
      required: false

  - type: dropdown
    id: affected-area
    attributes:
      label: Affected Component
      description: Which part of the application does this relate to?
      multiple: true
      options:
        - File Cleaner
        - Folder Cleaner
        - Orphan Cleaner
        - Game Optimizer
        - Optimization Suggestions
        - Options/Settings
        - Logging
        - UI/Theme
        - Localization
        - Performance
        - Cross-platform Compatibility
        - Documentation
        - Other
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important
        - Critical
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here
      placeholder: "Screenshots, examples from other tools, mockups, etc."
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - label: I would be willing to submit a pull request for this feature
          required: false
