"""English (US) translations for WoW Cleanup Tool."""

TRANSLATIONS = {
    "btn_browse": "Browse...",
    "btn_clear_log": "Clear Log",
    "btn_clear_persistent_log": "Clear Persistent Log",
    "btn_copy_log": "Copy to Clipboard",
    "btn_log_saved": "Log saved to: {}",
    "btn_no": "No",
    "btn_ok": "OK",
    "btn_remove_selected": "Remove Selected",
    "btn_reset_settings": "Reset Settings",
    "btn_save_log": "Save Log File",
    "btn_scan_files": "Scan Files",
    "btn_select_all_toggle": "Select All / Unselect All",
    "btn_toggle_theme": "Toggle Theme",
    "btn_yes": "Yes",
    "dep_install_complete": "Installation Complete",
    "dep_install_complete_msg": "Dependencies were successfully installed, but some packages\ntook longer than expected.\n\nThe application is now ready to use.",
    "dep_install_failed": "Installation Failed",
    "dep_install_failed_msg": "Failed to install required dependencies.\n\nThe application cannot run without these packages.\n\nPlease install manually:\npip install send2trash psutil Pillow",
    "dep_installing_count": "Installing {} required package(s)...",
    "dep_taking_longer": "Installation is taking longer than expected...",
    "dep_trying_stage": "Trying {} of {}...",
    "desc_file_cleaner": "Scan and remove unnecessary backup, temporary, and old files from your World of Warcraft installation.",
    "dev_startup_dependency_error": "Dependency error: {error}",
    "dev_startup_import_error": "Failed to import module: {module} ({error})",
    "dev_startup_localization_error": "Localization error: {error}",
    "dev_startup_settings_error": "Settings error: {error}",
    "startup_error_see_devlog": "Startup error. See the developer log for details.",
    "startup_success": "WoW Cleanup Tool initialized successfully.",
    "status_app_started": "Application started successfully!",
    "status_detecting_wow": "Detecting World of Warcraft installation...",
    "status_initializing": "Initializing...",
    "status_log_copied": "Log copied to clipboard",
    "status_log_deleted": "Log file deleted successfully",
    "status_settings_reset": "Settings have been reset to defaults",
    "status_settings_saved": "Settings saved. Closing application...",
    "status_validating_wow": "Validating WoW installation structure...",
    "system_default_font": "System Default",
    "tab_backup_old_cleaner": "Backup & Old File Cleaner",
    "tab_developer": "Developer Log",
    "tab_disabled_tooltip": "This feature requires a valid WoW installation path. Please use the Browse button to select your World of Warcraft folder.",
    "tab_file_cleaner": "File Cleaner",
    "tab_folder_cleaner": "Folder Cleaner",
    "tab_game_optimizer": "Game Optimizer",
    "tab_log": "User Log",
    "tab_optimization_suggestions": "Optimization Suggestions",
    "tab_orphan_cleaner": "Orphan Cleaner",
    "title_backup_warning": "Important: Backup Your Data",
    "title_dependencies": "Installing Dependencies",
    "title_license": "License Agreement",
    "title_main_window": "WoW Cleanup Tool",
    "title_multiple_installations": "Multiple WoW Installations Detected",
    "title_reset_settings": "Confirm Reset",
    "tooltip_browse_wow_folder": "Choose your main WoW folder (not a subfolder).",
    "tooltip_clear_log": "Clear the current session log.",
    "tooltip_clear_persistent_log": "Clear the persistent user log file (only available in append mode).",
    "tooltip_language_menu": "Select application language",
    "tooltip_log_timestamps": "User Log and Developer Log",
    "tooltip_user_log_only": "User Log Only",
    "version_alpha": "alpha version",
    "version_beta": "beta version",
    "version_stable": "stable release",
    "warning": "Warning",
    "warning_icon": "⚠",
    "wow_detected": "WoW installation detected at: {}",
    "wow_not_detected": "Could not automatically detect WoW installation",
    "wow_validated": "WoW installation validated. Found {} game version(s)",
}
