"""English (US) translations for WoW Cleanup Tool."""

TRANSLATIONS = {
    "btn_browse": "Browse...",
    "btn_copy_log": "Copy to Clipboard",
    "btn_log_saved": "Log saved to: {}",
    "btn_no": "No",
    "btn_ok": "OK",
    "btn_remove_selected": "Remove Selected",
    "btn_reset_settings": "Reset Settings",
    "btn_save_log": "Save Log File",
    "btn_scan_files": "Scan Files",
    "btn_select_all_toggle": "Select All / Unselect All",
    "btn_toggle_theme": "Toggle Theme",
    "btn_yes": "Yes",
    "desc_file_cleaner": "Scan and remove unnecessary backup, temporary, and old files from your World of Warcraft installation.",
    "dep_install_complete": "Installation Complete",
    "dep_install_complete_msg": "Dependencies were successfully installed, but some packages\ntook longer than expected.\n\nThe application is now ready to use.",
    "dep_install_failed": "Installation Failed",
    "dep_install_failed_msg": "Failed to install required dependencies.\n\nThe application cannot run without these packages.\n\nPlease install manually:\npip install send2trash psutil Pillow",
    "dep_installing_count": "Installing {} required package(s)...",
    "dep_taking_longer": "Installation is taking longer than expected...",
    "dep_trying_stage": "Trying {} of {}...",
    "error_prefix": "Error:",
    "error_scanning_version": "Error scanning {}: {}",
    "error_threadpool_fallback": "ThreadPoolExecutor failed, falling back to single-threaded: {}",
    "file_all_files": "All files",
    "file_text_files": "Text files",
    "flavor_beta": "Beta",
    "flavor_classic": "Classic",
    "flavor_classic_era": "Classic Era",
    "flavor_ptr": "Public Test Realm",
    "flavor_retail": "Retail (Live)",
    "invalid_wow_path": "Invalid WoW installation path",
    "label_append_log": "Append Log",
    "label_delete_mode": "Delete Mode:",
    "label_detected_installations": "Detected WoW Installation Paths:",
    "label_font": "Font:",
    "label_font_size": "Font Size:",
    "label_language": "Language:",
    "label_verbose_logging": "Verbose Logging",
    "label_wow_installation_path": "WoW Installation Path:",
    "license_accept": "Accept",
    "license_decline": "Decline",
    "license_file_not_found": "License file not found.",
    "log_delete": "Delete Log File",
    "log_delete_error": "Failed to delete log file: {}",
    "msg_backup_warning": "Before using this tool, it is highly recommended that you backup your WoW installation, especially your AddOns and WTF folders. This tool will move deleted files to the Recycle Bin, but it's always better to be safe.\n\nDo you want to continue?",
    "msg_license_instructions": "Please read and accept the license agreement to use this application.",
    "msg_multiple_installations": "Multiple World of Warcraft installations have been detected on your system. The game should only be installed in one location to function properly.",
    "msg_multiple_installations_instructions": "Please consolidate your World of Warcraft installation into a single directory. Move all game files from the additional installations to your main installation, then remove the duplicate folders.",
    "msg_reset_settings_confirm": 'Reset all settings to defaults?\n\nThis will:\n• Reset theme to Light\n• Reset font to System Default\n• Reset font size to 9\n• Reset delete mode to Trash\n• Enable verbose logging\n• DISABLE append log mode (logs will clear on restart)\n• Reset language to English\n• Re-enable all "don\'t show again" dialogs\n\nCached data (WoW path, existing logs) will be preserved.\n\nContinue?',
    "msg_wow_close_warning": "Please ensure World of Warcraft is closed before using this tool.\n\nThis prevents file conflicts and ensures all cleanup operations complete successfully.",
    "multiple_wow_detected": "Multiple WoW installations detected: {}",
    "option_delete_mode_permanent": "Delete Permanently",
    "option_delete_mode_trash": "Move to Trash",
    "option_dont_show_again": "Don't show this warning again",
    "option_language_english": "English",
    "option_license_dont_show": "Don't show this again (I accept the license)",
    "press_enter_to_exit": "Press Enter to exit...",
    "select_wow_folder": "Select World of Warcraft Installation Folder",
    "status_app_started": "Application started successfully!",
    "status_detecting_wow": "Detecting World of Warcraft installation...",
    "status_initializing": "Initializing...",
    "status_log_copied": "Log copied to clipboard",
    "status_log_deleted": "Log file deleted successfully",
    "status_settings_reset": "Settings have been reset to defaults",
    "status_settings_saved": "Settings saved. Closing application...",
    "status_validating_wow": "Validating WoW installation structure...",
    "system_default_font": "System Default",
    "tab_backup_old_cleaner": "Backup & Old File Cleaner",
    "tab_developer": "Developer",
    "tab_disabled_tooltip": "This feature requires a valid WoW installation path. Please use the Browse button to select your World of Warcraft folder.",
    "tab_file_cleaner": "File Cleaner",
    "tab_folder_cleaner": "Folder Cleaner",
    "tab_game_optimizer": "Game Optimizer",
    "tab_log": "Log",
    "tab_optimization_suggestions": "Optimization Suggestions",
    "tab_orphan_cleaner": "Orphan Cleaner",
    "title_backup_warning": "Important: Backup Your Data",
    "title_dependencies": "Installing Dependencies",
    "title_license": "License Agreement",
    "title_main_window": "WoW Cleanup Tool",
    "title_multiple_installations": "Multiple WoW Installations Detected",
    "title_reset_settings": "Confirm Reset",
    "tooltip_browse_wow_folder": "Choose your main WoW folder (not a subfolder).",
    "version_alpha": "alpha version",
    "version_beta": "beta version",
    "version_stable": "stable release",
    "warning": "Warning",
    "warning_icon": "⚠",
    "wow_detected": "WoW installation detected at: {}",
    "wow_not_detected": "Could not automatically detect WoW installation",
    "wow_validated": "WoW installation validated. Found {} game version(s)",
}
